version: '3'
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  kafka:
    image: bitnami/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
  redis:
    image: redis
    ports:
      - "6379:6379"